# Generated by Django 3.1.6 on 2021-02-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_no', models.IntegerField()),
                ('price', models.IntegerField(default=50)),
                ('expiry_date', models.CharField(max_length=120)),
            ],
        ),
    ]
