# Generated by Django 3.1.6 on 2021-03-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('phone_no', models.IntegerField()),
                ('Address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='mobile_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MobileOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_image', models.ImageField(upload_to='images')),
                ('price', models.CharField(max_length=120)),
                ('memory', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=120)),
                ('Battery', models.CharField(max_length=120)),
                ('Warranty', models.CharField(max_length=120)),
                ('mobile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.mobile_detail')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.status')),
            ],
        ),
    ]
