# Generated by Django 3.1.6 on 2021-03-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Account_no',
            field=models.IntegerField(max_length=18),
        ),
    ]
