# Generated by Django 3.1.6 on 2021-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_auto_20210326_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=120)),
                ('account_no', models.IntegerField()),
                ('IFSC_code', models.CharField(max_length=50)),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
