# Generated by Django 3.1.6 on 2021-03-26 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_auto_20210326_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='account_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(18)]),
        ),
    ]
