# Generated by Django 3.1.6 on 2021-03-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_auto_20210326_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='account_no',
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
    ]
